Tarea2/Tarea2/urls.py
from django.contrib import admin
from django.urls import path
from ORM_Django.views import menu, listarproducto, producto, editarproducto, eliminarproducto, cliente, listarcliente, \
    editarcliente, eliminarcliente, listarfactura, factura, eliminarfactura, editarfactura

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', menu, name='index'),
    path('producto/', producto, name='producto'),
    path('listarproducto/', listarproducto, name='listarproducto'),
    path('editarproducto/<int:id>/', editarproducto, name='editarproducto'),
    path('eliminarproducto/<int:id>', eliminarproducto, name='eliminarproducto'),

    path('cliente/', cliente, name='cliente'),
    path('listarcliente/', listarcliente, name='listarcliente'),
    path('editarcliente/<int:id>/', editarcliente, name='editarcliente'),
    path('eliminarcliente/<int:id>', eliminarcliente, name='eliminarcliente'),

    path('factura/', factura, name='factura'),
    path('listarfactura/', listarfactura, name='listarfactura'),
    path('editarfactura/<int:id>/', editarfactura, name='editarfactura'),
    path('eliminarfactura/<int:id>', eliminarfactura, name='eliminarfactura'),
]

Tarea2/ORM_Django/models.py
from django.db import models

# Create your models here.
class Producto(models.Model):
    descripcion = models.CharField(max_length=100)
    precio = models.FloatField(default=0)
    stock = models.IntegerField(default=0)
    iva = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'
        ordering = ["descripcion"]

    def __str__(self):
        return self.descripcion

class Cliente(models.Model):
    ruc = models.CharField(max_length=13)
    nombre = models.CharField(max_length=300)
    direccion = models.TextField(blank=True, null=True)
    producto = models.ManyToManyField(Producto)

    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'
        ordering = ["-nombre"]

    def __str__(self):
        return str(self.nombre)

class Factura(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete = models.CASCADE)
    fecha = models.DateField()
    total = models.FloatField(default=0)

class DetalleFactura(models.Model):
    factura=models.ForeignKey(Factura, on_delete= models.CASCADE)
    producto=models.ForeignKey(Producto, on_delete= models.CASCADE)
    cantidad = models.FloatField(default=0)
    precio = models.FloatField(default=0)
    subtotal = models.FloatField(default=0)
#Ingresar
#Modelo Producto
#P = Producto(descripcion='Aceite Girazol',precio=1.50,stock=2000)
#P.save()
#Producto.objects.create(descripcion='Coca Cola',precio=0.90,stock=10000)

#Modelo Cliente
#C = Cliente(ruc='0967456789001',nombre='Emily Anahi',direccion='Av. Juan Montalvo')
#C.save()
#C.producto.add(1)
#C2 = Cliente(ruc='0987654321001',nombre='Pedro Almeida',direccion='Pedro Carbo y Amazonas')
#C2.save()
#C2.producto.add(2)
#Cliente.objects.create(ruc='0987656788001',nombre='Vicente Mendoza',direccion='Los Helechos')
#C3 = Cliente.objects.get(id=3)
#C3.producto.add(1)

#Modelo Factura
#F = Factura(cliente=C,fecha='2019-04-27',total=15.80)
#F.save()
#F = Factura(cliente=C2,fecha='2020-03-22',total=35.90)
#F.save()
#F2 = Factura(cliente=C,fecha='2019-06-23',total=25.80)
#F2.save()
#Factura.objects.create(cliente=C2,fecha='2020-06-25',total=5.80)

#Modelo Detallefactura

#DT = DetalleFactura(factura=F,producto=P,cantidad=3,precio=11.97,subtotal=20)
#DT.save()
#DetalleFactura.objects.create(factura=F2,producto=P2,cantidad=2,precio=2.90,subtotal=5.8)

#Modificar
#Modelo Producto
#p = Producto.objects.get(id=1)
#p.precio=1.13
#p.save()
#Producto.objects.filter(id=1).update(precio=1.7)

#Modelo Cliente
#cli = Cliente.objects.get(id=1)
#cli.nombre = 'Anahi Yuxan'
#cli.save()
#Cliente.objects.filter(id=2).update(nombre='Juan Moran')


#Modulo Factura

#factu = Factura.objects.get(id=1)
#factu.total=23.90
#factu.save()
#Factura.objects.filter(id=2).update(total=55.88)


#Modulo factura
#detfac = DetalleFactura.objects.get(id=1)
#detfac.cantidad=1
#detfac.save()
#DetalleFactura.objects.filter(id=2).update(cantidad=2)

#Eliminar

#Modelo Producto
#ep = Producto.objects.get(id=1)
#ep.delete()
#Producto.objects.filter(id=2).delete()

# Modelo Cliente
#ec = Cliente.objects.get(id=1)
#ec.delete()
#Cliente.objects.filter(id=2).delete()

#Modelo Factura
#ef = Factura.objects.get(id=1)
#ef.delete()
#Factura.objects.filter(id=2).delete()


#Modelo DetalleFactura
#edp=DetalleFactura.objects.get(id=1)
#edp.delete()
#DetalleFactura.objects.filter(id=2).delete()

#Query de un Modelo
#DetalleFactura.objects.create(factura=F2,producto=Producto.objects.get(id=4),cantidad=2,precio=2.90,subtotal=5.8)
#p= Producto.objects.get(id=3)
#Producto.objects.filter(id__lte=3)
#Producto.objects.exclude(descripcion__icontains='Cola')
#Producto.objects.filter(id__gte=4)
#Producto.objects.filter(id__gte=4).values('id','descripcion')
#Producto.objects.filter(descripcion='Coca Cola').values('id','descripcion')

#Query de varios modelos relacionados
#DetalleFactura.objects.create(factura=F2,producto=Producto.objects.get(id=4),cantidad=2,precio=2.90,subtotal=5.8)
#p= Producto.objects.get(id=3)
#Producto.objects.filter(id__lte=3)
#Producto.objects.exclude(descripcion__icontains='Cola')
#Producto.objects.filter(id__gte=4)
#Producto.objects.filter(id__gte=4).values('id','descripcion')
#Producto.objects.filter(descripcion='Coca Cola').values('id','descripcion')
#Factura.objects.filter(cliente__nombre='Emily Anahi')
#c= Cliente.objects.get(nombre='Emily Anahi')
#c.factura_set.all()
#c.factura_set.filter(id=5)
#Factura.objects.select_related('cliente').filter(cliente__nombre='Emily Anahi')
#Cliente.objects.prefetch_related('producto').filter(nombre='Emily Anahi').values('nombre','producto__descripcion')

Tarea2/templates/cliente.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    {% load static %}
    <title>Vistazo de Django</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}"/>
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic"
          rel="stylesheet" type="text/css"/>
    <!-- Third party plugin CSS-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css"
          rel="stylesheet"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet"/>
</head>
<body id="page-top">
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">PROYECTO DE FACTURACION CON DJANGO </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>

    </div>
</nav>
<!-- Masthead-->
<header class="masthead">
    <div class="container">
        <ul>
            <l1><a href='/'>{{ Menu }}</a></l1>
            <l1><a href='/listarcliente'>/{{ Contacto }}</a></l1>

        </ul>
        <center><h1>{{ Contacto }}</h1></center>
        <form action="" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4"></div>
                <div class="col-md-4">{{ form.as_p }}
                    <button class="btn btn-primary" type="submit">{{ accion }}</button>
                </div>
                <div class="col-md-4"></div>

            </div>
        </form>
    </div>
</header>

<!-- Footer-->
<footer class="bg-light py-5">
    <div class="container">
        <div class="small text-center text-muted">UNEMI-CRUD</div>
    </div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
<!-- Third party plugin JS-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
<!-- Core theme JS-->
<script src="{% static "js/scripts.js" %}"></script>
</body>
<script>
    function soloLetras(e) {
        key = e.keyCode || e.which;
        tecla = String.fromCharCode(key).toLowerCase();
        letras = " áéíóúabcdefghijklmnñopqrstuvwxyz";
        especiales = "8-37-39-46";

        tecla_especial = false
        for (var i in especiales) {
            if (key == especiales[i]) {
                tecla_especial = true;
                break;
            }
        }

        if (letras.indexOf(tecla) == -1 && !tecla_especial) {
            return false;
        }
    }

    function soloNumeros(e) {
        var key = window.event ? e.which : e.keyCode;
        if (key < 48 || key > 57) {
            e.preventDefault();
        }
    }

    function soloNumerosdecimales(evt, input) {
        // Backspace = 8, Enter = 13, ‘0′ = 48, ‘9′ = 57, ‘.’ = 46, ‘-’ = 43
        var key = window.Event ? evt.which : evt.keyCode;
        var chark = String.fromCharCode(key);
        var tempValue = input.value + chark;
        if (key >= 48 && key <= 57) {
            if (filter(tempValue) === false) {
                return false;
            } else {
                return true;
            }
        } else {
            if (key == 8 || key == 13 || key == 0) {
                return true;
            } else if (key == 46) {
                if (filter(tempValue) === false) {
                    return false;
                } else {
                    return true;
                }
            } else {
                return false;
            }
        }
    }

    function filter(__val__) {
        var preg = /^([0-9]+\.?[0-9]{0,2})$/;
        if (preg.test(__val__) === true) {
            return true;
        } else {
            return false;
        }

    }
</script>
</html>

Tarea2/templates/eliminarcliente.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Eliminar {{Cliente.nombre}}</title>
</head>

<body>

    <h1>Eliminar {{Cliente.nombre}}</h1>
    <form action="" method="post">
        {% csrf_token %}
        <h1>Estas Seguro de Eliminar El Cliente: {{ Cliente.nombre }}</h1>
        <button type="submit">Eliminar</button>
        <button><a href="{% url 'listarcliente' %}">cancelar</a></button>
    </form>
</body>

</html>

Tarea2/templates/eliminarfactura.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Eliminar {{Factura.cliente}}</title>
</head>

<body>

    <h1>Eliminar {{Factura.cliente}}</h1>
    <form action="" method="post">
        {% csrf_token %}
        <h1>Estas Seguro de Eliminar la Factura del cliente: {{ Factura.cliente }}</h1>
        <button type="submit">Eliminar</button>
        <button><a href="{% url 'listarfactura' %}">cancelar</a></button>
    </form>
</body>

</html>

Tarea2/templates/eliminarproducto.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Eliminar {{Producto.descripcion}}</title>
</head>

<body>

    <h1>Eliminar {{Producto.nombre}}</h1>
    <form action="" method="post">
        {% csrf_token %}
        <h1>Estas Seguro de Eliminar El Producto: {{ Producto.descripcion }}</h1>
        <button type="submit">Eliminar</button>
        <button><a href="{% url 'listarproducto' %}">cancelar</a></button>
    </form>
</body>

</html>

Tarea2/templates/factura.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    {% load static %}
    <title>Vistazo de Django</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}"/>
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic"
          rel="stylesheet" type="text/css"/>
    <!-- Third party plugin CSS-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css"
          rel="stylesheet"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet"/>
</head>
<body id="page-top">
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">PROYECTO DE FACTURACION CON DJANGO </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>

    </div>
</nav>
<!-- Masthead-->
<header class="masthead">
    <div class="container">
        <ul>
            <l1><a href='/'>{{ Menu }}</a></l1>
            <l1><a href='/listarfactura'>/{{ Contacto }}</a></l1>

        </ul>
        <center><h1>{{ Contacto }}</h1></center>


        <form action="" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="form-group col-md-2">
                    <label for="inputEmail4">Factura</label>
                    {{ formde.factura }}
                </div>
                <div class="form-group col-md-4">
                    <label for="inputEmail4">Cliente</label>
                    {{ form.cliente }}
                </div>
                <div class="form-group col-md-3">
                    <label for="inputEmail4">Fecha</label>
                    {{ form.fecha }}
                </div>
                <div class="form-group col-md-3">
                    <label for="inputEmail4">SubTotal</label>
                    {{ formde.subtotal }}
                </div>

            </div>
            <div class="row">
                <div class="form-group col-md-3">
                    <label for="inputEmail4">Producto</label>
                    {{ formde.producto }}
                </div>
                <div class="form-group col-md-3">
                    <label for="inputPassword4">Cantidad</label>
                    {{ formde.cantidad }}
                </div>
                <div class="form-group col-md-3">
                    <label for="inputPassword4">Precio</label>
                    {{ formde.precio }}
                </div>
                <div class="form-group col-md-3">
                    <label for="inputPassword4">Total</label>
                    {{ form.total }}
                </div>
            </div>
            <div>
                <table class="table table-hover table-bordered table-sm" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th>
                            <center>Producto</center>
                        </th>
                        <th>
                            <center>Cantidad</center>
                        </th>
                        <th>
                            <center>Precio</center>
                        </th>
                        <th>
                            <center>Subtotal</center>
                        </th>
                        <th>
                            <center>Accion</center>
                        </th>
                    </tr>
                    </thead>

                    <body>
                    <tr>
                        <td>
                            <center></center>
                        </td>
                        <td>
                            <center></center>
                        </td>
                        <td>
                            <center></center>
                        </td>
                        <td>
                            <center></center>
                        </td>

                        <td>
                            <center>
                                <ul>
                                    <l1><a class="btn btn-primary"
                                           href="">Eliminar</a>
                                    </l1>
                                </ul>
                            </center>
                        </td>

                    </tr>
                    </body>

                </table>
            </div>
        </form>
    </div>
</header>

<!-- Footer-->
<footer class="bg-light py-5">
    <div class="container">
        <div class="small text-center text-muted">UNEMI-CRUD</div>
    </div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
<!-- Third party plugin JS-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
<!-- Core theme JS-->
<script src="{% static "js/scripts.js" %}"></script>
</body>
<script>
    $(document).ready(function () {
        var f = new Date();
        $('#id_fecha').val(f.getDate() + "/" + (f.getMonth() + 1) + "/" + f.getFullYear());
        $('#id_factura').val({{ idsig }})
    });
</script>

<script>
    function soloLetras(e) {
        key = e.keyCode || e.which;
        tecla = String.fromCharCode(key).toLowerCase();
        letras = " áéíóúabcdefghijklmnñopqrstuvwxyz";
        especiales = "8-37-39-46";

        tecla_especial = false
        for (var i in especiales) {
            if (key == especiales[i]) {
                tecla_especial = true;
                break;
            }
        }

        if (letras.indexOf(tecla) == -1 && !tecla_especial) {
            return false;
        }
    }

    function soloNumeros(e) {
        var key = window.event ? e.which : e.keyCode;
        if (key < 48 || key > 57) {
            e.preventDefault();
        }
    }

    function soloNumerosdecimales(evt, input) {
        // Backspace = 8, Enter = 13, ‘0′ = 48, ‘9′ = 57, ‘.’ = 46, ‘-’ = 43
        var key = window.Event ? evt.which : evt.keyCode;
        var chark = String.fromCharCode(key);
        var tempValue = input.value + chark;
        if (key >= 48 && key <= 57) {
            if (filter(tempValue) === false) {
                return false;
            } else {
                return true;
            }
        } else {
            if (key == 8 || key == 13 || key == 0) {
                return true;
            } else if (key == 46) {
                if (filter(tempValue) === false) {
                    return false;
                } else {
                    return true;
                }
            } else {
                return false;
            }
        }
    }

    function filter(__val__) {
        var preg = /^([0-9]+\.?[0-9]{0,2})$/;
        if (preg.test(__val__) === true) {
            return true;
        } else {
            return false;
        }

    }
</script>
</html>

Tarea2/templates/listarcliente.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    {% load static %}
    <title>Vistazo de Django</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}"/>
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic"
          rel="stylesheet" type="text/css"/>
    <!-- Third party plugin CSS-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css"
          rel="stylesheet"/>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.21/datatables.min.css"/>

    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet"/>
</head>
<body id="page-top">
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container">
        <ul>
            <l1><a class="navbar-brand js-scroll-trigger" href='/'>{{ Menu }}</a></l1>
            <l1><a class="navbar-brand js-scroll-trigger" href='/listarcliente'>/{{ Contacto }}</a></l1>

        </ul>
    </div>

</nav>
<!-- Masthead-->
<header class="">

</header>
<div class="masthead">

    <center><h1> {{ Contacto }}s</h1></center>
    <a class="btn btn-primary" href="{% url 'cliente' %}">Nuevo</a>
    <table id="dtBasicExample" class="table table-hover table-bordered table-sm" cellspacing="0" width="100%">
        <thead>
        <tr>
            <th>
                <center>Nombre</center>
            </th>
            <th>
                <center>Direccion</center>
            </th>
            <th>
                <center>Ruc</center>
            </th>
            <th>
                <center>Producto</center>
            </th>
            <th>
                <center>Acciones</center>
            </th>
        </tr>
        </thead>

        <body>
        {% for cliente in clientes %}
            <tr>
                <td>
                    <center>{{ cliente.nombre }}</center>
                </td>
                <td>
                    <center>{{ cliente.direccion }}</center>
                </td>
                <td>
                    <center>{{ cliente.ruc }}</center>
                </td>
                <td>
                    {% for producto in cliente.producto.all %}
                        <center>{{ producto.descripcion }}</center>
                    {% endfor %}


                </td>
                <td>
                    <center>
                        <ul>
                            <l1><a class="btn btn-primary"
                                   href="{% url 'editarcliente' cliente.id %}">Modificar</a>
                            </l1>
                            <l1><a class="btn btn-primary"
                                   href="{% url 'eliminarcliente' cliente.id %}">Eliminar</a>
                            </l1>
                        </ul>
                    </center>
                </td>

            </tr>
        {% endfor %}
        </body>

    </table>
    <footer class="bg-light py-5">
        <div class="container">
            <div class="small text-center text-muted">UNEMI-CRUD</div>
        </div>
    </footer>
</div>
<!-- Footer-->

<!-- Bootstrap core JS-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
<!-- Third party plugin JS-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
<!-- Core theme JS-->

<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.21/datatables.min.js"></script>

<script src="{% static "js/scripts.js" %}"></script>
</body>
<script>
    $(document).ready(function () {
        $('#dtBasicExample').DataTable();
        $('.dataTables_length').addClass('bs-select');
    });
</script>
</html>